# Generated by Django 6.0.2 on 2026-02-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_fooditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
